sudo: required
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  chrome: stable
  code_climate:
    repo_token: e87e6bf1c253e0555437ebd23235fdfe2749b889358e7c6d100e4ea5b4f2e091
language: node_js
node_js:
  - "6"
  - "7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - yarn build
script:
  - yarn test
after_script:
  - cat coverage/lcov.info | codeclimate
