sudo: required
dist: trusty
addons:
  code_climate:
    repo_token: e87e6bf1c253e0555437ebd23235fdfe2749b889358e7c6d100e4ea5b4f2e091
language: node_js
node_js:
  - "8"
before_script:
  - yarn build
script:
  - yarn test
after_script:
  - cat coverage/lcov.info | codeclimate
